$editor=kitty -e nvim
$fileManager=kitty -e yazi
$menu=wofi --show drun
$terminal=kitty
decoration {
  rounding=10
  blur {
    size = 3
    passes = 3
    ignore_opacity = true
  }
}

dwindle {
  default_split_ratio=1
  force_split=0
  preserve_split=true
  smart_resizing=true
  smart_split=true
}

input {
  kb_layout=gb
}

misc {
  disable_splash_rendering=true
  disable_watchdog_warning=true
}
# Animation demos below available on https://cubic-bezier.com/
# {"ease":".25,.1,.25,1","Hypr":"0,0.75,0.15,1","ease-in":".42,0,1,1","ease-out":"0,0,.58,1","ease-in-out":".42,0,.58,1","easeOutBack-ish":"0.175,0.885,0.32,1.275","elastic":"0.68,-0.55,0.265,1.55","easeOut-quintish":"0.22,0.61,0.36,1","google":"0.4,0,0.2,1","apple":"0.25,0.46,0.45,0.94","bounce":"0.34,1.56,0.64,1","custom":"0.2,0.3,0,1"}
bezier = custom, 0.2, 0.3, 0, 1
animation = windows, 1, 8, custom, slide
animation = layers, 1, 8, custom, slide
animation = workspaces, 1, 8, custom, slidefadevert
bind=SUPER, Q, exec, uwsm app -- $terminal
bind=SUPER, M, exit,
bind=SUPER, R, exec, uwsm app -- $menu
bind=SUPER, C, killactive,
bind=SUPER, B, exec, uwsm app -- brave
bind=SUPER, T, togglefloating,
bind=SUPER, E, exec, uwsm app -- $fileManager
bind=SUPER, F, fullscreen, 1
bind=SUPER, N, exec, uwsm app -- $editor
bind=SUPER, L, exec, hyprlock
bind=SUPER, P, exec, mirror-toggle
bind=SUPER, S, togglesplit,
bind=SUPER SHIFT, F, fullscreen, 0
bind=SUPER, left, movefocus, l
bind=SUPER, right, movefocus, r
bind=SUPER, up, movefocus, u
bind=SUPER, down, movefocus, d
bind=SUPER, 1, workspace, 1
bind=SUPER, 2, workspace, 2
bind=SUPER, 3, workspace, 3
bind=SUPER, 4, workspace, 4
bind=SUPER, 5, workspace, 5
bind=SUPER, 6, workspace, 6
bind=SUPER, 7, workspace, 7
bind=SUPER, 8, workspace, 8
bind=SUPER, 9, workspace, 9
bind=SUPER, 0, workspace, 10
bind=SUPER SHIFT, 1, movetoworkspace, 1
bind=SUPER SHIFT, 2, movetoworkspace, 2
bind=SUPER SHIFT, 3, movetoworkspace, 3
bind=SUPER SHIFT, 4, movetoworkspace, 4
bind=SUPER SHIFT, 5, movetoworkspace, 5
bind=SUPER SHIFT, 6, movetoworkspace, 6
bind=SUPER SHIFT, 7, movetoworkspace, 7
bind=SUPER SHIFT, 8, movetoworkspace, 8
bind=SUPER SHIFT, 9, movetoworkspace, 9
bind=SUPER SHIFT, 0, movetoworkspace, 10
bind=SUPER SHIFT, left, swapwindow, l
bind=SUPER SHIFT, right, swapwindow, r
bind=SUPER SHIFT, up, swapwindow, u
bind=SUPER SHIFT, down, swapwindow, d
bind=SUPER CTRL, left,  movewindow, l
bind=SUPER CTRL, right, movewindow, r
bind=SUPER CTRL, up,    movewindow, u
bind=SUPER CTRL, down,  movewindow, d
bind=, XF86MonBrightnessUp, exec, brightnessctl set +5%
bind=, XF86MonBrightnessDown, exec, brightnessctl set 5%-
bind=, XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bind=, XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bind=, XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bind=, XF86AudioPlay, exec, playerctl play-pause
bind=, XF86AudioNext, exec, playerctl next
bind=, XF86AudioPrev, exec, playerctl previous
bindl=,switch:on:Lid Switch,exec,lid-toggle close
bindl=,switch:off:Lid Switch,exec,lid-toggle open
bindm=SUPER, mouse:272, movewindow
bindm=SUPER, mouse:273, resizewindow
exec-once=hyprlock --immediate
exec-once=uwsm app -- waybar
monitor=,preferred,auto,1
